### ISSUE TITLE
this._removeUniqueSelectionListener is not a function

### ISSUE THREAD

**Issue by MikeDabrowski** [help-me-mom/ng-mocks#10180]
### Description of the bug

When using MockBuilder and MockRenderFactory the error `this._removeUniqueSelectionListener is not a function` appears.

### An example of the bug

I started writing a test using MockBuilder. Set the builder in the beforeEach, added one it with MockRender. Test worked. Then I wanted to add another test case, similar setup, slightly different inputs. So converted to MockRenderFactory as in [here](https://ng-mocks.sudo.eu/api/MockRender#factory). 

```bash
Failed Tests:
 BatchInfoComponent
    alert translations
       Should always use fallback alert text for unexpected (or new) rejection codes
          Chrome Headless 129.0.0.0 (Windows 10)
             36) TypeError: this._removeUniqueSelectionListener is not a function
                at BatchInfoComponent.call [as ngOnDestroy] (node_modules/@angular/cdk/fesm2022/accordion.mjs:138:14)
                at executeOnDestroys (node_modules/@angular/core/fesm2022/core.mjs:11352:32)        
                at cleanUpView (node_modules/@angular/core/fesm2022/core.mjs:11255:9)
                at destroyViewTree (node_modules/@angular/core/fesm2022/core.mjs:11086:17)
                at destroyLView (node_modules/@angular/core/fesm2022/core.mjs:11228:9)
                at ViewRef$1.destroy (node_modules/@angular/core/fesm2022/core.mjs:14123:9)
                at ComponentRef.destroy (node_modules/@angular/core/fesm2022/core.mjs:16847:23)     
                at PseudoApplicationComponentFixture.destroy (node_modules/@angular/core/fesm2022/testing.mjs:287:31)
                at PseudoApplicationComponentFixture.destroy (node_modules/@angular/core/fesm2022/testing.mjs:418:15)
                at resetFixtures (node_modules/ng-mocks/index.mjs:1:110908)
```

Ok, maybe factory is bad. Lets try copy pasted its

```bash
LOG MESSAGES FOR: Chrome Headless 129.0.0.0 (Windows 10) INSTANCE #: 44682028
   'Error during cleanup of component', Object{component: r{}, stacktrace: TypeError: this._removeUniqueSelectionListener is not a function
TypeError: this._removeUniqueSelectionListener is not a function
    at BatchInfoComponent.call [as ngOnDestroy] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/fesm2022/accordion.mjs:138:14)
    at executeOnDestroys (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:11352:32)
    at cleanUpView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:11255:9)
    at destroyViewTree (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:11086:17)
    at destroyLView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:11228:9)
    at ViewRef$1.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:14123:9)
    at ComponentRef.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:16847:23)
    at PseudoApplicationComponentFixture.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:287:31)
    at PseudoApplicationComponentFixture.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:418:15)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:2105:25}
```
It work when I have only one `it` enabled.

test setup:
```typescript
beforeEach(() =>
    MockBuilder(BatchInfoComponent)
      .beforeCompileComponents((testBed) => {
        testBed.configureTestingModule({
          schemas: [NO_ERRORS_SCHEMA],
        });
      })
      .replace(BrowserAnimationsModule, NoopAnimationsModule)
      .provide(provideTranslocoForTesting())
      .keep(TranslocoModule)
      .keep(AlertComponent)
      .provide(provideMarkdown())
      .provide(provideTranslocoMissingHandler(MissingTranslationHandler))
      .provide({ provide: IS_PRODUCTION, useValue: true })
  );

describe('', () => {
  it('My Test', () => {
    const fixture = MockRender(BatchInfoComponent, {
        batchDetails,
        batchStatistics,
        batchEvents,
        isLoaded: true,
      });
    expect(component).toBeDefined();
  })
})
```
ng-mocks v 14.13.1
angular 18.2.7

The component being tested extends CdkAccordionItem from AngularMaterial

### Expected vs actual behavior

Expected it to just work

**Comment by MikeDabrowski** [comment]
Ok, got it working by adding `.keep(AccordionModule)`. This issue might be specific to my case only.
