### ISSUE TITLE
Bug: Standalone component mocking/tests does not work in Angular 15

### ISSUE THREAD

**Issue by dolanmiu** [help-me-mom/ng-mocks#4395]
### Description of the bug

Standalone component mocking/tests does not work in Angular 15. From following the guide in the official docs:

![Untitled](https://user-images.githubusercontent.com/2917613/205414938-3eec865d-580d-4dd0-8aff-543e8717ce2a.png)

#### My test

```ts
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [HomeComponent],
      imports: [
        MockComponent(FeaturedProductComponent),
        MockComponent(NewsletterComponent),
        MockComponent(CarouselComponent),
      ],
      providers: [MockProvider(ShopifyService, { allProducts$: EMPTY }), ...createFirebaseTestingModules()],
    }).compileComponents();
  });
```

Result:

```ts
        Error: Unexpected "HomeComponent" found in the "declarations" array of the "TestBed.configureTestingModule" call, "HomeComponent" is marked as standalone and can't be declared in any NgModule - did you intend to import it instead (by adding it to the "imports" array)?
            at forEach (node_modules/@angular/core/fesm2020/testing.mjs:25454:19)
            at Array.forEach (<anonymous>)
            at assertNoStandaloneComponents (node_modules/@angular/core/fesm2020/testing.mjs:25451:11)
            at TestBedCompiler.configureTestingModule (node_modules/@angular/core/fesm2020/testing.mjs:25513:13)
            at TestBedImpl.call (node_modules/@angular/core/fesm2020/testing.mjs:26505:23)
            at TestBedImpl.configureTestingModule (node_modules/ng-mocks/index.mjs:1:61051)
            at Function.call (node_modules/@angular/core/fesm2020/testing.mjs:26345:37)
            at Function.call (node_modules/ng-mocks/index.mjs:1:75960)
            at Function.TestBed (node_modules/ng-mocks/index.mjs:1:61196)
            at UserContext.<anonymous> (projects/front/src/app/home/home.component.spec.ts:17:11)
```

**Comment by satanTime** [comment]
Hi @dolanmiu,

if `HomeComponent` is a standalone component, why do you specify it in `declarations` instead of `imports`?
