### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by e-oz** [help-me-mom/ng-mocks#5240]
With TypeScript 5.0.2 functions `MockService()`  and `MockComponent()` generate this error:

```
RangeError: Maximum call stack size exceeded

      at Object.getResolution (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/common/ng-mocks-universe.ts:121:38)
      at updated (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:47:7)
      at d (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:80:19)
      at value (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:51:40)
      at d (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:80:19)
      at value (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:51:40)
      at d (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:80:19)
      at value (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:51:40)
      at d (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:80:19)
      at value (../../node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts:51:40)
...
```

node v19.8.1

**Comment by satanTime** [comment]
Hey there, thank you for the report.

It looks similarly to #5240.

**Comment by satanTime** [comment]
[v14.7.2](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.7.2) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by vinlos** [comment]
I still have problems to mock some components. I've not been able to isolate the issue to make it easily reproducible yet. Any one experiencing the same?
