### ISSUE TITLE
Bug: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lneumeier** [help-me-mom/ng-mocks#5262]
After the update from 14.5.0 to 14.5.1 (#4564) I'm getting following error

```
Maximum call stack size exceeded
        at Object.isExcludedDef (node_modules/ng-mocks/index.mjs:1:6637)
        at node_modules/ng-mocks/index.mjs:1:10494
        at t (node_modules/ng-mocks/index.mjs:1:10437)
        at node_modules/ng-mocks/index.mjs:1:10528
        at t (node_modules/ng-mocks/index.mjs:1:10437)
        at node_modules/ng-mocks/index.mjs:1:10528
        at t (node_modules/ng-mocks/index.mjs:1:10437)
        at node_modules/ng-mocks/index.mjs:1:10528
        at t (node_modules/ng-mocks/index.mjs:1:10437)
        at node_modules/ng-mocks/index.mjs:1:10528
```

on some of my unittests. Do you have any idea what I should look for?

PS:

I'm using 
```
declarations: [MockComponents(Example1Component, Example2Component)],
```
and 
```
declarations: [MockComponent(ExampleComponent)],
````

**Comment by satanTime** [comment]
[v14.7.2](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.7.2) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by lneumeier** [comment]
Thank you for the quick fix.

**Comment by satanTime** [comment]
Not at all, please let me know if it solves your issue.

**Comment by lneumeier** [comment]
Yes, the issue is solved. Thank you.

**Comment by satanTime** [comment]
Cool, thanks! Stay in touch!
