### ISSUE TITLE
Bug: "component threw errors during cleanup" with Angular Material

### ISSUE THREAD

**Issue by souiddhaker** [help-me-mom/ng-mocks#5838]
### Description of the bug

When using the ng-mocks in conjunction with Angular Material components, a bug has been observed regarding the cleanup of fixtures. The issue occurs when attempting to clean up a fixture that contains an Angular Material component, resulting in unexpected behavior or errors.

### An example of the bug

Encountering an error while testing a component with MatTabs. 

`Error: 1 component threw errors during cleanup
    at TestBedRender3.destroyActiveFixtures (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/testing.mjs:1842:1)
    at TestBedRender3.resetTestingModule (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/testing.mjs:1677:1)
    at Function.resetTestingModule (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/testing.mjs:1620:1)
    at Function.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/index.js:1:41391)
    at Function.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ng-mocks/index.js:1:153078)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/testing.mjs:2006:1)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
    at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)`

### Expected vs actual behavior

The fixture should be properly cleaned up, and any resources associated with the Angular Material component should be released. The cleanup process should not result in any errors or unexpected behavior.

**Comment by satanTime** [comment]
Hi @souiddhaker, could you provide a min repo with the issue? 

ng-mocks has e2e tests with material and there are no errors, so it should be something related to your setup of the project.

**Comment by satanTime** [comment]
Hi @souiddhaker, feel free to reopen the issue when you have more details how to reproduce it.
