### ISSUE TITLE
Bug: `RangeError: Maximum call stack size exceeded` when encountering circular reference in component imported using `forwardRef`

### ISSUE THREAD

**Issue by alexciesielski** [help-me-mom/ng-mocks#6143]
### Description of the bug

I am trying to write a test for a recursive standalone component, which imports a parent component, which imports this component, using `forwardRef(() => ParentComponent)` in the `imports: []` array of the Component decorator declaration, like below

```ts
@Component({
  selector: 'y42-parent',
  standalone: true,
  imports: [
    CommonModule,
    ChildComponent,
  ],
})
export class ParentComponent {}
```

```ts
@Component({
  selector: 'y42-child',
  standalone: true,
  imports: [
    CommonModule,
    forwardRef(() => ParentComponent),
  ],
})
export class ChildComponent {}
```

```ts
beforeEach(() => MockBuilder(ChildComponent));
```

```
RangeError: Maximum call stack size exceeded

at queueTypesFromModulesArrayRecur (../../node_modules/@angular/core/fesm2015/testing.mjs:23577:49)
at ../../node_modules/@angular/core/fesm2015/testing.mjs:23608:29
    at Array.forEach (<anonymous>)
at queueTypesFromModulesArrayRecur (../../node_modules/@angular/core/fesm2015/testing.mjs:23602:34)
at ../../node_modules/@angular/core/fesm2015/testing.mjs:23608:29
    at Array.forEach (<anonymous>)
at queueTypesFromModulesArrayRecur (../../node_modules/@angular/core/fesm2015/testing.mjs:23602:34)
at ../../node_modules/@angular/core/fesm2015/testing.mjs:23608:29
    at Array.forEach (<anonymous>)
at queueTypesFromModulesArrayRecur (../../node_modules/@angular/core/fesm2015/testing.mjs:23602:34)
at ../../node_modules/@angular/core/fesm2015/testing.mjs:23608:29
    at Array.forEach (<anonymous>)
```

If I comment out the import of the forwardRef the test correctly instantiates the component so it's definitely because of that.
I tried every possible way using `.mock`, `.replace`, `.keep` - but everything results in the above error.

I'm on `ng-mocks 14.7.1` and `angular 15.2.0`

**Comment by alexciesielski** [comment]
I just updated to latest `ng-mocks` and I still get the error

**Comment by satanTime** [comment]
Hi @alexciesielski,

thank you for reporting the issue.
It looks like an angular issue.

I tested on `ng-mocks@14.11.0` and `angular@15.2.10` and it works correctly.

Could you confirm it still fails on your side?
The test I'm using is:

```ts
import {CommonModule} from '@angular/common';
import {Component, forwardRef,} from '@angular/core';
import {MockBuilder, MockRender, ngMocks} from 'ng-mocks';

@Component({
  selector: 'y42-child',
  standalone: true,
  imports: [
    CommonModule,
    forwardRef(() => ParentComponent),
  ],
  template: 'ChildComponent'
})
export class ChildComponent {}

@Component({
  selector: 'y42-parent',
  standalone: true,
  imports: [
    CommonModule,
    ChildComponent,
  ],
  template: 'ParentComponent',
})
export class ParentComponent {}

describe('my sandbox', () => {
  describe('ChildComponent', () => {
    beforeEach(() => MockBuilder(ChildComponent));

    it('should render ChildComponent', () => {
      const fixture = MockRender(ChildComponent);

      // Asserting it got the right paramId.
      expect(ngMocks.formatText(fixture)).toEqual('ChildComponent');
    });
  });

  describe('ParentComponent',() => {
    beforeEach(() => MockBuilder(ParentComponent));

    it('should render ParentComponent', () => {
      const fixture = MockRender(ParentComponent);

      // Asserting it got the right paramId.
      expect(ngMocks.formatText(fixture)).toEqual('ParentComponent');
    });
  });
});
```

the result:
```
> ng test --ts-config ./tsconfig.json --progress=false

15 11 2023 14:37:43.200:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9877/
15 11 2023 14:37:43.202:INFO [launcher]: Launching browsers ChromeCi with concurrency unlimited
15 11 2023 14:37:43.205:INFO [launcher]: Starting browser ChromeHeadless
15 11 2023 14:37:47.090:INFO [Chrome Headless 101.0.4950.0 (Mac OS 10.15.7)]: Connected on socket 9TlMSNuu1kSnwDp7AAAB with id 90245406
TOTAL: 4 SUCCESS

> jest --config jest.config.ts

jest-haste-map: Haste module naming collision: a15
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/package.json
    * <rootDir>/dist/lib/package.json

 PASS  src/app/app.component.spec.ts (5.507 s)
 PASS  src/issue/test.spec.ts

Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        7.466 s
Ran all test suites.
```

**Comment by satanTime** [comment]
I re-checked this on March 27, 2026 using the exact standalone `forwardRef(() => ParentComponent)` cycle from the issue.

Results from the repo wrapper/container workflow:
- current `upstream/main`: targeted root Karma repro passed
- Angular 15 matrix (`@angular/* 15.2.10`): targeted Jasmine repro passed
- Angular 15 matrix (`@angular/* 15.2.10`): targeted Jest repro passed

That matches the earlier maintainer verification in this thread that the same scenario works on `ng-mocks@14.11.0` with Angular 15.2.10, so this no longer looks actionable on supported releases.

Please verify against the latest `ng-mocks` release, `v14.15.2` from March 15, 2026. If you can still reproduce it there, please reopen with a minimal reproduction and the exact Angular / ng-mocks versions.

**Comment by satanTime** [comment]
Follow-up verification found that the exact reported standalone cycle still overflows with current ng-mocks on Angular 15.2.0 in both Jasmine and Jest. The recursion occurs inside Angular TestBed before ng-mocks can apply its overrides; Angular tracked it in angular/angular#49469 and fixed it in Angular 15.2.4 (angular/angular@bae6b5ceb16bd87c8146aa29564a8d29135a6f95).

The same regression passes unchanged on Angular 15.2.4 and newer. A library-side workaround would require mutating Angular private component definitions or changing MockRender lifecycle semantics, so no ng-mocks runtime hotfix is appropriate. #14513 documents the minimum Angular patch and corrects the regression-test context.

If this still fails after upgrading all @angular/* packages to a matching 15.2.4 or newer patch, please reopen with a minimal reproduction and the exact Angular package versions.

**Comment by satanTime** [comment]
[v14.16.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.16.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
