### ISSUE TITLE
Bug: MockInstance won't override values for InjectionToken

### ISSUE THREAD

**Issue by jacques-ro** [help-me-mom/ng-mocks#6556]
### Description of the bug

ng-mocks Version: 14.11.0

I am providing an InjectionToken in MockBuilder. Then, either via MockInstance or alternatively via providers in MockRender, I provide a different value for the token.

This value never reaches the fixture.

### An example of the bug

```typescript

fdescribe('simple token tests', () => {
  MockInstance.scope();

  beforeEach(() =>
    MockBuilder(MockService, [DependentClass]).provide({
      provide: MOCK_TOKEN,
      useValue: 'pizza',
    })
  );

  it('should override injection token providers via MockInstance', () => {
    const overriddenValue = 'pasta';

    MockInstance(MOCK_TOKEN, () => overriddenValue);

    MockRender(MockService);

    const tokenValue = ngMocks.get(MOCK_TOKEN);

    expect(tokenValue).toEqual(overriddenValue); // pizza should have changed to pasta, but didn't
  });

  it('should override injection token providers via providers in MockRender', () => {
    const overriddenValue = 'pasta';

    MockRender(
      MockService,
      {},
      {
        providers: [
          {
            provide: MOCK_TOKEN,
            useValue: overriddenValue,
          },
        ],
      }
    );

    const tokenValue = ngMocks.get(MOCK_TOKEN);

    expect(tokenValue).toEqual(overriddenValue); // pizza should have changed to pasta, but didn't
  });

  it('should override class providers via providers in MockRender', () => {
    const overriddenValue = { mockReplacement: true };
    MockInstance(DependentClass, () => overriddenValue);

    MockRender(MockService, {}, { providers: [{ provide: DependentClass, useValue: overriddenValue }] });
    const classValue = ngMocks.findInstance(DependentClass);

    expect(classValue).toBe(overriddenValue); // ref comparison succeeds
  });

```

Output (shortened): 

```bash

Chrome Headless 116.0.5845.97 (Windows 10) simple token tests should override injection token providers via MockInstance FAILED
        Error: Expected 'pizza' to equal 'pasta'.
            at <Jasmine>
            at UserContext.apply (projects/apps/supman/src/features/planning-documents/detail-view/state/tests/detail-view.effects.spec.ts:56:24)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
Chrome Headless 116.0.5845.97 (Windows 10) simple token tests should override injection token providers via providers in MockRender FAILED
        Error: Expected 'pizza' to equal 'pasta'.
            at <Jasmine>
            at UserContext.apply (projects/apps/supman/src/features/planning-documents/detail-view/state/tests/detail-view.effects.spec.ts:78:24)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
Chrome Headless 116.0.5845.97 (Windows 10): Executed 3 of 160 (2 FAILED) (skipped 157) (0.269 secs / 0.2 secs)
TOTAL: 2 FAILED, 1 SUCCESS

```

### Expected vs actual behavior

MockInstance and MockRender providers override the token value from 'pizza' to 'pasta'

**Comment by satanTime** [comment]
Hi @jacques-ro,

this is expected, because in your tests `MOCK_TOKEN` isn't a mock, but a normal provider with `useValue`, whereas [`MockInstance`](https://ng-mocks.sudo.eu/api/MockInstance) defines customizations for **mock** declarations.


To fix this, you need to use [`MockProvider`](https://ng-mocks.sudo.eu/api/MockProvider) to let `ng-mocks` know that `MOCK_TOKEN` should be a mock:

```ts
    MockBuilder(MockService, [DependentClass]).provide(
      MockProvider(MOCK_TOKEN, 'pizza'),
    })
```
