### ISSUE TITLE
Bug: Incompatibility of MockComponent with new viewChild signal function

### ISSUE THREAD

**Issue by mh-ahs** [help-me-mom/ng-mocks#8634]
### Description of the bug

Testing standalone components with nested components that use the new viewChild signal feature is currently not possible if the nested component should be mocked.

I'm not sure if ngMocks can do anything about it or if its an angular-core related problem.

### An example of the bug

Link: https://stackblitz.com/edit/github-6eneyd?file=src%2Ftest.spec.ts
I added a "NestedComponent" to the default example and replaced the module-based definitions with a simple standalone definition. 

### Expected vs actual behavior

Using the Signal implementation leads to
`TypeError: Cannot read properties of undefined (reading 'Symbol(SIGNAL)')`
Switching the implementation from Signal to Decorator lets test run fine,

**Comment by GipHub123** [comment]
I can confirm this one 👍  Having same problems after the change.

**Comment by c-harding** [comment]
Temporary workaround: use `MockBuilder#replace`

```ts
@Component({
  selector: 'app-nested',
  standalone: true,
  template: ``,
})
class NestedComponentStub {
  public readonly anchor = signal(new ElementRef(undefined)).asReadonly();
  public readonly name = input.required<string>();
}

describe('my sandbox', () => {
  beforeEach(() =>
    MockBuilder(TargetComponent).replace(NestedComponent, NestedComponentStub)
  );
```

**Comment by c-harding** [comment]
@satanTime this seems to be a better fix: simply remove the view queries, as they’ll always be null anyway

https://github.com/help-me-mom/ng-mocks/blob/282cbf0a6d1bb3ae78c6c8fb48f753bb02ca8d33/libs/ng-mocks/src/lib/common/decorate.queries.ts#L22-L39

```diff
  const generateFinalQueries = (queries: { 
    [key: string]: Query; 
  }): [Array<[string, Query & { ngMetadataName?: string }]>, string[]] => { 
    const final: Array<[string, Query & { ngMetadataName?: string }]> = []; 
    const scanKeys: string[] = []; 
   
    for (const key of Object.keys(queries)) { 
      const query: Query & { ngMetadataName?: string } = queries[key]; 
-     final.push([key, query]); 
   
      if (!query.isViewQuery && !isInternalKey(key)) { 
+       final.push([key, query]);
        scanKeys.push(key); 
        final.push([`__ngMocksVcr_${key}`, cloneVcrQuery(query)]); 
      } 
    } 
   
    return [final, scanKeys]; 
  }; 
```

**Comment by andreandersson** [comment]
This will be fixed by the same fix as https://github.com/help-me-mom/ng-mocks/issues/7976, is my guess.

**Comment by renanaragao** [comment]
Good evening, any news?

**Comment by mishahrokhola** [comment]
Hello, any updates on this issue?

**Comment by LukasMachetanz** [comment]
I guess #8895 is a similar problem.

**Comment by SereetsiKC** [comment]
The fix here is not to mock the component but pass it into your test declarations with you parent component

**Comment by satanTime** [comment]
Sorry for the delay. I'll take a look closer next week.

**Comment by LukasMachetanz** [comment]
@satanTime, did you already have a chance to look into it?

**Comment by pcbowers** [comment]
Another workaround I found until this is fixed:

```ts
MockInstance(YourComponent, 'viewChildElement', signal(MockService(ElementRef)));
// OR
MockInstance(YourComponent, 'viewChildElement', signal(MockService(TemplateRef)));
// OR
MockInstance(YourComponent, 'viewChildElement', signal(MockComponent(ChildComponent)));
```

**Comment by LukasMachetanz** [comment]
@satanTime, sorry to bother you again, but do you have any updates on this? I guess you have currently limited time to work on request like this, right?

**Comment by Francesco-Borzi** [comment]
Confirmed. If you try to mock a component that uses a `viewChild` signal inside, it will give error.

cc @satanTime

**Comment by zargham-leanix** [comment]
I can confirm, happening for me as well.

**Comment by dankerk** [comment]
Hey @Francesco-Borzi fancy seeing you here :D

+1 on this issue

**Comment by Martinspire** [comment]
So @satanTime is this on the list to fix soon as well?

**Comment by alixroyere** [comment]
> Another workaround I found until this is fixed:
> 
> MockInstance(YourComponent, 'viewChildElement', signal(new ElementRef(document.createElement('div'))));


Ok so this workaround works but I had some difficulties to apply it. So here is a more verbose explanation that is working in my case:

```typescript

describe('my tests', () => {
  // Define a scope to auto-clean mocked instance see https://ng-mocks.sudo.eu/api/MockInstance/#scope
  MockInstance.scope();

  beforeEach(async () => {
       // Put expected TestBed conf WITH the broken MockComponent(MyComponent)
       await TestBed.configureTestingModule [...]
       
       // Override the viewChild element with a viewChild-matching-type mock
       // (can be ElementRef as in the previous answer or Component, etc depending on your code)
       MockInstance(MyComponent, 'myViewChild', signal({} as MyViewChildComponent));
  });

  it('my test', () => {
      // test
  });
});
```

**Comment by tibztibz** [comment]
any news for the resolution of this  issue ?

**Comment by satanTime** [comment]
in todo

**Comment by renanaragao** [comment]
My case is the same as the first post

**Comment by c-harding** [comment]
Mine too, but with `viewChild.required`

**Comment by tibztibz** [comment]
the same problem with contentChild too. An exemple :

```ts
import { CommonModule } from '@angular/common'
import {
    ChangeDetectionStrategy,
    Component,
    Directive,
    contentChild,
    ElementRef,
    inject,
    viewChild,
} from '@angular/core'


@Directive({
    selector: 'uiButtonStart',
})
export class ButtonStartDirective {}


@Component({
    selector: 'button[ui-button]',
    templateUrl: './button.component.html',
    styleUrls: ['./button.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
    standalone: true,
    imports: [CommonModule],
})
export class ButtonComponent implements ElementRef  {
    
    #elementRef = inject(ElementRef)

    viewChildProp = viewChild<ElementRef>('buttonText')

    contentChildProp = contentChild(ButtonStartDirective, { descendants: true })
    nativeElement: HTMLElement = this.#elementRef.nativeElement

}


@Component({
    template : `
       <button ui-button>
            <mat-icon uiButtonStart>edit</mat-icon>
            edit
       </button>
    `
    changeDetection: ChangeDetectionStrategy.OnPush,
    standalone: true,
    imports: [CommonModule, MatIcon],
})
export class ButtonEditComponent implements ElementRef  {
    
    #elementRef = inject(ElementRef)

    viewChildProp = viewChild<ElementRef>('buttonText')

    contentChildProp = contentChild(ButtonStartDirective, { descendants: true })
    nativeElement: HTMLElement = this.#elementRef.nativeElement

}


describe('ButtonEditComponent', () => {
    ngMocks.faster()
    MockInstance.scope()

    beforeAll(() => MockBuilder(ButtonEditComponent)
        .keep(CommonModule)
        .mock(ButtonComponent)
        .mock(MatIcon)
    )


    it('test', () => {

        const fixture = MockRender(DataHeaderDeletionComponent)
        const component = fixture.point.componentInstance

        expect(component).toBeTruthy()
    })

})


```

**Comment by kheos31** [comment]
You should test query signatures :

- viewChild
- viewChild.required 
- viewChildren
- viewChildren.required 
- contentChild
- contentChild.required
- contentChildren
- contentChildren.required

In addition to these signatures, as @tibztibz mentioned in these scenarios, you have additional options for these signatures : 

- locators: https://angular.dev/guide/components/queries#query-locators
- options: https://angular.dev/guide/components/queries#query-options

thx @satanTime

**Comment by yarychh** [comment]
my case is: standalone component imports a module (SharedFeatureModule) which has a component that uses signal-based `viewChild`.

`
await TestBed.configureTestingModule({
      imports: [SomeWrapperComponent, MockModule(SharedFeatureModule)],
    }).compileComponents();
`

thx @satanTime

**Comment by Martinspire** [comment]
Has there been any progress on this?

**Comment by FrankMerema** [comment]
Having the same issue as mentioned above, it's related to contentChild.required in my case. The code is super easy as describe in the other cases :)

**Comment by Nvveen** [comment]
Any progress? This  is breaking our CI, and after the breaking bug of 5 months ago concerning the `standalone` flag, this is getting a bit tiresome.

**Comment by Martinspire** [comment]
Since angular is working to move everything to signals, I kinda don't really like to use complex workarounds for this. I want to make components that use these contentChildren, viewChild, etc and right now the only solution I see is to either move to the old and soon-to-be-outdated version of @contentchildren, or use the complex way of overriding components by using overrideComponents and use that syntax from Spectator

```
    overrideComponents: [
      [
        FilterPresetFormComponent,
        {
          remove: {
            imports: [SelectDisplayComponent],
          },
          add: {
            imports: [MockSelectDisplayComponent],
          },
        },
      ],
    ],
```

I don't really see another way of using common components in many tests without the hassle of overriding them overly complex with standalone.

**Comment by Martinspire** [comment]
> [@Martinspire](https://github.com/Martinspire) I found a workaround using the builder by incorporating [@c-harding](https://github.com/c-harding) 's solution:
> 
> * Make the sub component
> * `.replace(Component, StubComponent)`
> 
> This reduced the boilerplate a lot.

Yeah I know that is an option, but I always use createComponentFactory for my components as I need to often mock a lot of items it just makes more sense to me to use that, but it doesn't have the handy dandy override. Plus some components I use frequently (like a selectbox) would require replacement everywhere.

**Comment by Nvveen** [comment]
> Yeah I know that is an option, but I always use createComponentFactory for my components as I need to often mock a lot of items it just makes more sense to me to use that, but it doesn't have the handy dandy override. Plus some components I use frequently (like a selectbox) would require replacement everywhere.

I use `createComponentFactory` too:
```
const dependencies = MockBuilder(Component).mock(...).build()
const createComponent = createComponentFactory({ component: Component, ...dependenciess })
```

**Comment by Martinspire** [comment]
It would still be better if the bug was fixed. Did anybody get some progress on this already?

**Comment by c-harding** [comment]
@Martinspire @Nvveen my current solution is as follows: I centrally define the mocks for all child queries at the bottom of `test.ts`. This way, when the components are mocked, these fields are set to signals.

```ts
// test.ts
const mockViewChild = <T extends HTMLElement>() => signal<ElementRef<T>>(undefined as never);
MockInstance(MyComponent, 'modal', mockViewChild());
MockInstance(OtherComponent, 'videoEl', mockViewChild<HTMLVideoElement>());
```

Of course, it would be preferable if this could properly be fixed, for example using the solution in https://github.com/help-me-mom/ng-mocks/pull/8771

**Comment by Nvveen** [comment]
> [@Martinspire](https://github.com/Martinspire) [@Nvveen](https://github.com/Nvveen) my current solution is as follows: I centrally define the mocks for all child queries at the bottom of `test.ts`. This way, when the components are mocked, these fields are set to signals.
> 
> // test.ts
> const mockViewChild = <T extends HTMLElement>() => signal<ElementRef<T>>(undefined as never);
> MockInstance(MyComponent, 'modal', mockViewChild());
> MockInstance(OtherComponent, 'videoEl', mockViewChild<HTMLVideoElement>());
> Of course, it would be preferable if this could properly be fixed, for example using the solution in [#8771](https://github.com/help-me-mom/ng-mocks/pull/8771)

Fantastic workaround, because when this gets fixed, you can just remove the overrides from `test.ts`.

**Comment by JustinPierce** [comment]
I've found that, when working with `contentChild` and `contentChildren`, none of the workarounds for `viewChild` and `viewChildren` seem to work. The only thing I've found to work around this is to define a stub component have ng-mocks replace it.

If my component looks like this:

```TS
@Component({
    selector: "my-component",
    standalone: true,
    templateUrl: "./my-component.component.html",
    styleUrls: ["./my-component.component.scss"],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MyComponent {
    readonly myContentChild = contentChild(WhateverType);
}
```

My stub component might look like this:

```TS
@Component({
    selector: "my-component",
    standalone: true,
    template: "<ng-content></ng-content>",
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MockOfMyComponent {
    readonly myContentChild = signal<WhateverType | undefined>(undefined);
}
```

And in `test.ts`, I globally replace this component:

```TS
ngMocks.globalReplace(MyComponent, MockOfMyComponent);
```

**Comment by tibztibz** [comment]
any news ?

**Comment by Brian-Hofmann** [comment]
+1

**Comment by HansKrywalsky** [comment]
@satanTime can you share any progress, do you need additional information or support?

**Comment by yktoo** [comment]
With the latest Angular 20 release it becomes an increasingly serious problem, hindering the use of `MockComponent()` more and more often. @satanTime is there any chance of having this fixed?

**Comment by mchlroy** [comment]
Here are my workarounds for anyone interested, also works for **ContentChild** and **ContentChildren**. 

**Disclaimer**: Hacky, not perfect and done for my immediate purposes, unsure if it covers all cases and configurations.

**Utils**
```ts
interface PropDecoratorFactory {
    type?: { prototype: { ngMetadataName?: string } };
    args: (Type<any> | string | { isSignal?: boolean })[];
}

const getPropMetadata = (def: Type<any>): Record<string, [PropDecoratorFactory]> | undefined => {
    if ('propDecorators' in def && def.propDecorators) {
        return def.propDecorators as Record<string, [PropDecoratorFactory]>;
    }
    return undefined;
};

const isSignal = (arg: any): boolean => {
    return arg && typeof arg === 'object' && 'isSignal' in arg && arg.isSignal === true;
};

const queryTypes = new Set(['ViewChild', 'ViewChildren', 'ContentChild', 'ContentChildren']);

/**
 * Retrieves the signal-based queries from a component's property metadata.
 * @param comp - The Angular component type to inspect.
 */
export const getSignalBasedQueries = (comp: Type<any>): Record<string, { type: string }> | undefined => {
    const propMetadata = getPropMetadata(comp);
    if (!propMetadata) {
        return {};
    }
    const queries: Record<string, any> = {};
    for (const [propName, decorators] of Object.entries(propMetadata)) {
        const decorator = decorators[0];
        const propType = decorator.type?.prototype?.ngMetadataName;
        if (propType && queryTypes.has(propType) && decorator.args.length > 1 && isSignal(decorator.args[1])) {
            queries[propName] = {
                type: propType,
            };
        }
    }
    return Object.keys(queries).length > 0 ? queries : undefined;
};

/**
 * Utility function to retrieve host directives from a given Angular directive type.
 * @param dir - The Angular directive or component type to inspect.
 */
export const getHostDirectives = (dir: Type<any>): Array<any> | undefined => {
    const possibleMetadataKeys = ['ɵcmp', 'ɵdir'];
    for (const key of possibleMetadataKeys) {
        if (key in dir && 'hostDirectives' in (dir as any)[key]) {
            return (dir as any)[key].hostDirectives as Array<any>;
        }
    }
    return undefined;
};

/**
 * Creates a mock signal that can be used to replace query signals in tests.
 */
export const createQuerySignalMock = (): Signal<undefined> => {
    const theSignal = signal(undefined);
    const signalSymbol = Object.getOwnPropertySymbols(theSignal)[0];
    if (signalSymbol) {
        (theSignal as any)[signalSymbol]._dirtyCounter = { update: jest.fn() }; // Mock the update method to avoid errors in tests;
    }
    return theSignal;
};

const mockSignalBasedQueries = (component: Type<any>): void => {
    const signalBasedQueries = getSignalBasedQueries(component);
    if (signalBasedQueries) {
        for (const [propName, metadata] of Object.entries(signalBasedQueries)) {
            MockInstance(component, propName, createQuerySignalMock());
            if (metadata.type === 'ContentChild' || metadata.type === 'ContentChildren') {
                // ng-mocks creates a property with a prefix `__ngMocksVcr_` for ContentChild/ContentChildren queries, found that out
                // by inspecting the metadata of a mocked component by MockComponent ('__prop__metadata__' property).
                MockInstance(component, `__ngMocksVcr_${propName}`, createQuerySignalMock());
            }
        }
    }
};
```

**Mock methods**
```ts
/**
 * Mocks a component using {@link MockComponent}, but also fixes the `Cannot read properties of undefined (reading 'Symbol(SIGNAL)')`
 * error when mocking directives that use signal-based queries.
 * @param component - The Angular component type to mock.
 */
export const mockComponent = <T>(component: Type<T>): Type<MockedComponent<T>> => {
    // Fix the "Cannot read properties of undefined (reading 'Symbol(SIGNAL)')" error when mocking components that uses signal-based queries.
    mockSignalBasedQueries(component);

    const hostDirectives = getHostDirectives(component);
    for (const hostDirective of hostDirectives || []) {
        mockSignalBasedQueries(hostDirective.directive);
    }

    return MockComponent(component);
};

/**
 * Mocks a directive using {@link MockDirective}, but also fixes the `Cannot read properties of undefined (reading 'Symbol(SIGNAL)')`
 * error when mocking directives that use signal-based queries.
 * @param directive - The Angular directive type to mock.
 */
export const mockDirective = <T>(directive: Type<T>): Type<MockedDirective<T>> => {
    // Fix the "Cannot read properties of undefined (reading 'Symbol(SIGNAL)')" error when mocking directives that uses signal-based queries.
    mockSignalBasedQueries(directive);

    const hostDirectives = getHostDirectives(directive);
    for (const hostDirective of hostDirectives || []) {
        mockSignalBasedQueries(hostDirective.directive);
    }
    return MockDirective(directive);
};
```

**Comment by fredericojesus** [comment]
@satanTime ..........................................

**Comment by Martinspire** [comment]
I've made a discussion about the state of the library. Lets separate that from the issues: https://github.com/help-me-mom/ng-mocks/discussions/12111

**Comment by MikeDabrowski** [comment]
> Here are my workarounds for anyone interested, also works for **ContentChild** and **ContentChildren**.

Your workaround works for me for the viewChild/Children but unfortunately breaks for contentChild/Children used with string selector.

Changes to improve:
```ts
export const getSignalBasedQueries = (
  comp: Type<any>,
): Record<string, { type: string; selector?: string }> | undefined => {
  const propMetadata = getPropMetadata(comp);
  if (!propMetadata) {
    return {};
  }
  const queries: Record<string, any> = {};
  for (const [propName, decorators] of Object.entries(propMetadata)) {
    const decorator = decorators[0];
    const propType = decorator.type?.prototype?.ngMetadataName;
    if (
      propType &&
      queryTypes.has(propType) &&
      decorator.args.length > 1 &&
      isSignal(decorator.args[1])
    ) {
      queries[propName] = {
        type: propType,
      };
      if (decorator.args[0] && typeof decorator.args[0] === 'string') {
        queries[propName].selector = decorator.args[0];
      }
    }
  }
  return Object.keys(queries).length > 0 ? queries : undefined;
};

...

const mockSignalBasedQueries = (component: Type<any>): void => {
  const signalBasedQueries = getSignalBasedQueries(component);
  if (signalBasedQueries) {
    for (const [propName, metadata] of Object.entries(signalBasedQueries)) {
      MockInstance(component, propName, createQuerySignalMock());
      if (
        metadata.type === 'ContentChild' ||
        metadata.type === 'ContentChildren'
      ) {
        // ng-mocks creates a property with a prefix `__ngMocksVcr_` for ContentChild/ContentChildren queries, found that out
        // by inspecting the metadata of a mocked component by MockComponent ('__prop__metadata__' property).
        MockInstance(
          component,
          `__ngMocksVcr_${propName}`,
          createQuerySignalMock(),
        );
      }
      if (metadata.selector) {
        MockInstance(
          component,
          `__mockTpl_key_${metadata.selector}`,
          createQuerySignalMock(),
        );
      }
    }
  }
};
```

How I found it:  
Got classic error `Cannot read properties of undefined (reading 'Symbol(SIGNAL)')` with stacktrace.
```
 at ɵɵcontentQuerySignal (node_modules/@angular/core/fesm2022/debug_node.mjs:25875:5)
 at Object.contentQueries (ng:///MockOfListComponent.js:35:9)
```
Opened test in karma in browser, opened dev tools, ctrl+p and opened `MockOfListComponent.js:35`. It looked like:
```ts
if (rf & 1) {
        jit___contentQuerySignal_6(dirIndex,ctx.headerTemplate,_c0,4);
        jit___contentQuerySignal_6(dirIndex,ctx.__ngMocksVcr_headerTemplate,_c0,4,
            jit_ViewContainerRef_7);
        jit___contentQuerySignal_6(dirIndex,ctx.__mockTpl_key_heads,_c0,4);
      }
```
The `jit___contentQuerySignal_6` was in fact calling `ɵɵcontentQuerySignal` passing undefined in place of target. When I put breakpoints in `ɵɵcontentQuerySignal` I saw that it worked first two times and then failed. That means the `ctx.__mockTpl_key_heads` was undefined. I was able to put a breakpoint one level higher and inspected the ctx which indeed did have `headerTemplate` and `__ngMocksVcr_headerTemplate` but did not have `__mockTpl_key_heads`.

From that point it was easy to modify the workaround functions to get them to create that property too.

**Comment by BojanKogoj** [comment]
@MikeDabrowski Your solution works, but I get
>  MockInstance: side effects have been detected (MyComponent). Forgot to add MockInstance.scope() or to call MockInstance.restore()?

I'll try to find out what the problem is

**Comment by BojanKogoj** [comment]
Adding the following (to setup-jest.ts) fixed the issue above
```ts
afterEach(MockInstance.restore);
beforeEach(MockInstance.remember);
```

Although it caused an issue with `fakeAsync`, it still works as a temporary fix. We don't use MockBuilder btw

**Comment by MikeDabrowski** [comment]
Thanks for the hint. I only very briefly hit that error and it went too quickly for me to even try to do anything about it. For me it wasn't in `fakeAsync`.

**Comment by tabanliviu** [comment]
@mchlroy @MikeDabrowski amazing work
I've cobbled together both solutions and used jest module mock to enhance the mock function from MockBuilder so we can seamlessly upgrade our tests now and not have to wait for when ng-mocks fixes this
it only supports `.mock(Component)` or `.mock(Directive)`
```typescript
jest.mock('ng-mocks', () => {
  const actualNgMocks = jest.requireActual('ng-mocks');

  const OriginalMockBuilder = actualNgMocks.MockBuilder;

  function ExtendedMockBuilder(...args: any[]) {
    const original = OriginalMockBuilder(args);

    const originalMock = original.mock;
    const originalKeep = original.keep;

    original.mock = function extendedMock(...parameters: any[]) {
      if (parameters && parameters.length === 1) {
        const def = parameters[0];

        if (isNgDef(def, 'c')) {
          return originalKeep.apply(original, [mockComponent(def)]);
        } else if (isNgDef(def, 'd')) {
          return originalKeep.apply(original, [mockDirective(def)]);
        }
      }

      return originalMock.apply(original, parameters);
    };

    return original;
  }
  ExtendedMockBuilder.prototype = OriginalMockBuilder.prototype;
  ExtendedMockBuilder.extend = OriginalMockBuilder.extend;

  Object.defineProperty(actualNgMocks, 'MockBuilder', {
    get(): any {
      return ExtendedMockBuilder;
    },
  });

  return actualNgMocks;
});
```

it also needs either 
```typescript
MockInstance.scope();
```

or

```typescript
afterEach(MockInstance.restore);
beforeEach(MockInstance.remember);
``` 
like @BojanKogoj mentioned

**Comment by Martinspire** [comment]
Does this mean that all the new signals are now usable with ngmocks automocked features again (mockcomponent, mockpipe, mockdirective)? And what about the new signal forms?

**Comment by tibztibz** [comment]
Great news ! So when arrive the next release ?

**Comment by JLa2r** [comment]
Hooray! I just tested this and my experience with this issue has been resolved with the `14.15.1` release!  🥇

**Comment by satanTime** [comment]
[v14.15.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.15.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
