### ISSUE TITLE
Bug: InputSignal not working when using NgMocks on a component imported from an external library

### ISSUE THREAD

**Issue by iamkinetic** [help-me-mom/ng-mocks#9698]
### Description of the bug

MockComponent on component imported from an external library does not work with InputSignal.

### An example of the bug

This is the simplified imported component definition:
```typescript
export declare class SomeComponent {
    isDisabled: InputSignal<boolean>;
    isInProgress: boolean;
}
```
Used like this: 
```html
 <some-component [isDisabled]="true" [isInProgress]="true" />
```

The `isInProgress` is using the `@Input()` decorator and is correctly working/rendering.
The isDisabled is a signal input and doesn't seem to be correctly rendered/working.

```
 Error: NG0303: Can't bind to 'isDisabled' since it isn't a known property of 'some-component' (used in the 'TestComponent' component template).
        1. If 'some-component' is an Angular component and it has the 'isDisabled' input, then verify that it is included in the '@Component.imports' of this component.
        2. If 'some-component' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component.
        error properties: Object({ code: 303 })
            at reportUnknownPropertyError (node_modules/@angular/core/fesm2022/core.mjs:10087:15)
            at handleUnknownPropertyError (node_modules/@angular/core/fesm2022/core.mjs:10083:5)
            at elementPropertyInternal (node_modules/@angular/core/fesm2022/core.mjs:12061:17)
            at ɵɵproperty (node_modules/@angular/core/fesm2022/core.mjs:22458:9)
            at templateFn (ng:///CitizenPortalSelectionComponent.js:25:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11620:9)
            at refreshView (node_modules/@angular/core/fesm2022/core.mjs:13238:13)
            at detectChangesInView (node_modules/@angular/core/fesm2022/core.mjs:13454:9)
            at detectChangesInViewIfAttached (node_modules/@angular/core/fesm2022/core.mjs:13414:5)
```

If I remove the [IsDisabled]="true" from the html, the page renders correctly and the unit test are ok.

If I copy the component from the library directly in my angular project, the InputSignal is correctly working with MockComponent.  Is something missing from the external library or is MockComponent not able to read the InputSignal from an exported component?

My unit test are using karma/jasmine (still using TestBed).  The project itself is correctly running and the binding on the InputSignal is working outside of the unit tests.

The components library and my project are both using Angular 18 and i'm using ngMocks latest version.

**Comment by mishahrokhola** [comment]
have the same problem

**Comment by iamkinetic** [comment]
@mishahrokhola Did you find any workaround?

**Comment by mishahrokhola** [comment]
@iamkinetic no. The only 1 thing is not to mock the component

**Comment by iamkinetic** [comment]
@satanTime Do you think it's something we could try to fix (and create a PR if we find a fix)?

Do you have any pointer at where in the code we would have to look?

**Comment by jjatczak** [comment]
I ran into the same problem and to be honest I'm not sure if this library already officially supports signal inputs. The documentation doesn't mention anything about it, additionally you won't find any references to signal inputs in the library code.

**Comment by rainscha** [comment]
Same Problem

**Comment by thiboot** [comment]
Same here

**Comment by okamiconcept** [comment]
I think there is the same kind of problem when using `ngMocks.output('component-selector-from-external-library', 'selected');`

The error here : `Cannot find selected output via ngMocks.output`

(The same output mock with the same component but internal in the application will work)

**Comment by satanTime** [comment]
Hi all. Give me please time on the weekend. I'll check PRs and fix this.

**Comment by atomicrobokid** [comment]
@satanTime is there any update on this please?

Looks like there was a PR from last year to address signal inputs that has never been merged:
https://github.com/help-me-mom/ng-mocks/pull/8818

**Comment by satanTime** [comment]
Hi all, could you also post as many code examples as you have with the issue and use-cases? So it would be easier for me to cover all of them with one attempt.

**Comment by kheos31** [comment]
Hello, you could try to use MockComponent on SplitComponent from angular-split: https://github.com/angular-split/angular-split/blob/main/projects/angular-split/src/lib/split/split.component.ts

**Comment by iamkinetic** [comment]
@satanTime I've created this small project to demonstrate the project.

https://github.com/iamkinetic/NgMocksBugs

AppComponent is using six differents components:
1. From an external library using a @Input
2. From an external library using a signal input
3. From an external library using a model signal
4. From an internal component using a @input
5. From an internal component using a signal input
6. From an internal component using a model signal

The internal components have the exact same code as the ones from the external library.

Tests 2 and 3 are failing.

**Comment by kbrn-gh** [comment]
Hello everyone! Same issue on my project. 
We upgraded Angular version from v17 to v19 and previously working unit tests (ng-mocks + jest) have started to fail.

From the investigation in my case the issue is in the usage of [ngx-valdemort](https://www.npmjs.com/package/ngx-valdemort) library, which uses `[control]` and `[controlName]` inputs as new **signal inputs**.

From the comments above I suppose ng-mocks is not quite friendly with `InputSignal` yet.

Test suit setup fragment:
```
beforeEach(() => {
  return MockBuilder(TestableStandaloneComponent)
    .provide({
      provide: Service1,
      useClass: Service1Stub,
    })
   ...
});
```

Ngx Valdemort's ValidationErrorsComponent .d.ts fragment:
```
export declare class ValidationErrorsComponent implements DoCheck {
  /**
   * The FormControl, FormGroup or FormArray containing the validation errors.
   * If set, the controlName input is ignored
   */
  control: import("@angular/core").InputSignal<AbstractControl<any, any> | null>;
  /**
   * The name (or the index, in case it's contained in a FormArray) of the FormControl, FormGroup or FormArray containing the validation
   * errors.
   * Ignored if the control input is set, and only usable if the control to validate is part of a control container
   */
  controlName: import("@angular/core").InputSignal<string | number | null>;
}
```

Error message in terminal
```
NG0303: Can't bind to 'control' since it isn't a known property of 'val-errors' (used in the 'TestableStandaloneComponent' component template).
  1. If 'val-errors' is an Angular component and it has the 'control' input, then verify that it is included in the '@Component.imports' of this component.
  2. If 'val-errors' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
  3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component.
```

Adding of .keep() / .mock() for `ValdemortModule` doesn't help.

important from package.json:
```
deps:
"@angular/core": "19.2.2",
"ngx-valdemort": "~13.0.0",

devDeps:
"ng-mocks": "^14.12.2",
```

As of workarounds I see for now only to rewrite test suit initialization using native Angular approach via `TestBed.configureTestingModule().compileComponent()`, but it's super unwanted option, because the problem is __global__.

Please, join the conversation and share your with situation. We all interested in fastest resolution of the problem. 

Thanks to the library authors and contributors.

**Comment by wamasimba** [comment]
Yeah, this is a real big issue for us as well.
In my opinion input signals are the only way to implement new components, but `ngMocks` not supporting input signals severly reduces its usefulness and applicability as a package,

**Comment by sgbrown** [comment]
@satanTime Any updates on this issue with InputSignals?

I've really enjoyed and appreciated what ngmocks has to offer, but this incompatibility with signals is starting to become more of an issue for my projects. Any progress would be very much appreciated.

**Comment by satanTime** [comment]
Hey. It's my nest issue to fix. But I struggle to dedicate enough time to that. 

I guess you noticed that renovate stopped working. Now that should be fixed first.

**Comment by evtk** [comment]
> As of workarounds I see for now only to rewrite test suit initialization using native Angular approach via `TestBed.configureTestingModule().compileComponent()`

You would still need to mock the directives from the ngx-valdemort package in that native approach right? And using MockDirective / MockComponent would not work for those.

I have used migrated a shared part of an Angular application to an Angular library only to stumble now on this exact same problem. 

I tried to solve it by doing a `globalKeep` in the setup-jest.ts` on all components and directives coming from my new library. But the issue here is that some of the components use services from that library as well, and they aren't provided. So it would mean I have to alter every test involved to provide a mock of that used service. Cumbersome.

Anyone found a nice hacky solution while @satanTime is working on getting this fixed?

**Comment by wamasimba** [comment]
Right now, in more than 50% of the tests in many apps I am involved with, `ng-mocks` has to be taken out, as using input signals has been the standard. Since more and more basic components use input signals in them, this will soon grow to 100%, at which time, we'll rip out ng-mocks completely... Unless,.... input  signals are supported very, very soon...

**Comment by khalic-lab** [comment]
Hi, this feature is really essential, would be great to have it implemented so we don't have to stop using ng-mocks

**Comment by iamkinetic** [comment]
@satanTime I've greatly appreciate this library over the years and I appreciate all of you work, but It would be really nice to know if signals are going to be supported anytime soon?  Like the previous comments, I'm also at the point where my team and I need to decide if we need to work on removing ngMocks from out tests or not.

Signals have been the biggest changes in the Angular world over the last few years and it's really a blocker that we can't use them with NgMocks.  Can you really say it supports Angular 17-18-19-20 if it doesn't work properly with signals?

I'm still willing to try to help modify the code to support them if you can give me some pointer.

**Comment by wvankoppen** [comment]
> [@satanTime](https://github.com/satanTime) I've greatly appreciate this library over the years and I appreciate all of you work, but It would be really nice to know if signals are going to be supported anytime soon? Like the previous comments, I'm also at the point where my team and I need to decide if we need to work on removing ngMocks from out tests or not.
> 
> Signals have been the biggest changes in the Angular world over the last few years and it's really a blocker that we can't use them with NgMocks. Can you really say it supports Angular 17-18-19-20 if it doesn't work properly with signals?
> 
> I'm still willing to try to help modify the code to support them if you can give me some pointer.

+1

**Comment by jtuds** [comment]
> [@satanTime](https://github.com/satanTime) I've greatly appreciate this library over the years and I appreciate all of you work, but It would be really nice to know if signals are going to be supported anytime soon? Like the previous comments, I'm also at the point where my team and I need to decide if we need to work on removing ngMocks from out tests or not.
> 
> Signals have been the biggest changes in the Angular world over the last few years and it's really a blocker that we can't use them with NgMocks. Can you really say it supports Angular 17-18-19-20 if it doesn't work properly with signals?
> 
> I'm still willing to try to help modify the code to support them if you can give me some pointer.

+1 - we are at the point where without some movement on this we have no choice but to remove ng-mocks from our apps as the problem will only get worse as Signals become more commonly used

**Comment by Deepaksingh-bhandari** [comment]
> [@satanTime](https://github.com/satanTime) I've greatly appreciate this library over the years and I appreciate all of you work, but It would be really nice to know if signals are going to be supported anytime soon? Like the previous comments, I'm also at the point where my team and I need to decide if we need to work on removing ngMocks from out tests or not.
> 
> Signals have been the biggest changes in the Angular world over the last few years and it's really a blocker that we can't use them with NgMocks. Can you really say it supports Angular 17-18-19-20 if it doesn't work properly with signals?
> 
> I'm still willing to try to help modify the code to support them if you can give me some pointer.

+1 - This issue is a big hindrance in usage of this library for angular applications going forward. We will have to remove it as well since we don't have any clarity on when this issue will be fixed.

**Comment by Watercycle** [comment]
I published a possible solution [here](https://github.com/help-me-mom/ng-mocks/pull/11909) that seems to work well enough for my team's usages.

---

To re-state two alternative workarounds that I saw mentioned in other issues:
1. Specify `MockBuilder(AppComponent).keep(MyLibComponent)` and deal with the chain of mocking.
2. Specify a default mock via [globalReplace](https://ng-mocks.sudo.eu/api/ngMocks/globalReplace/) that mirrors your real component's interface. Example below:

```ts
// ng-mocks-signals-workaround.ts

/** @see ComponentUsingSignalsComponent */
@Component({ selector: 'component-using-signals', template: '<ng-content></ng-content>' })
export class MockComponentUsingSignalsComponent {
  @Input() sameNameAsInputSignal!;
}

/**
 * ng-mocks doesn't support signals yet. So, we manually mock out
 * any components rendering sub-components that use signals by default.
 *
 * @see https://github.com/help-me-mom/ng-mocks/issues/9698
 */
export function mockComponentsUsingSignalsInNgMocks(): void {
  ngMocks.globalReplace(ComponentUsingSignalsComponent, MockComponentUsingSignalsComponent);
}
```
Then you would call `mockComponentsUsingSignalsInNgMocks()` in your `test.ts` file.

---

Also want to restate that this is a cool library that I hope sticks around!

**Comment by iamkinetic** [comment]
@satanTime : @Watercycle pull request is fixing all of the problems mentionned in this issue.

My team has also been working on its own fix over the last few weeks that also seems to fix the problems with external components, models, ContentChild and ContentChildren.

**Comment by evtk** [comment]
+1 for @Watercycle PR with fix. Just applied it to my repo and tests are green again. Awesome job!

one note: It doesn't seem to handle aliasing of signal inputs.

**Comment by Watercycle** [comment]
> It doesn't seem to handle aliasing of signal inputs.

@evtk Do you have a MRE (minimal reproducible example)? It could also be a version-specific issue.

---

I added an alias to one of my library component's inputs, referenced the library component in one of my app components (using the new alias), called `MockRender`, and verified that the html from the library component was mocked out. On the "0.0.1" package, that is. Double-checking my code changes, it is for sure correctly passing along `templateName` (`alias`).

That said, in NG19 importing `NgTemplateOutlet` into a standalone component seems to break `reflectComponentType`, so I wouldn't be surprised for there to be other weird edge-cases. Odds are we'll want to treat anything too weird as separate follow-up issues and lean on the `globalReplace` / manual mock components workaround until figuring out what's wrong.

**Comment by GITOrion8112** [comment]
This issue might also explain the errors when rendering a Component that uses the new Material Timepicker component. Thie Timepicker Component uses Input Signals as opposed to the Datepicker Component which still uses the @Input parameters.

console.error
    NG0303: Can't bind to 'matTimepicker' since it isn't a known property of 'input' (used in the 'Event' component template).
    1. If 'input' is an Angular component and it has the 'matTimepicker' input, then verify that it is included in the '@Component.imports' of this component.
    2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component.

console.error
    NG0303: Can't bind to 'htmlFor' since it isn't a known property of 'mat-timepicker-toggle' (used in the 'Event' component template).
    1. If 'mat-timepicker-toggle' is an Angular component and it has the 'htmlFor' input, then verify that it is included in the '@Component.imports' of this component.
    2. If 'mat-timepicker-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component.

**Comment by Martinspire** [comment]
I've made a discussion about the state of the library. Lets separate that from the issues: https://github.com/help-me-mom/ng-mocks/discussions/12111

**Comment by sgbrown** [comment]
@satanTime Could you please publish a new release of ng-mocks so the fix for this issue is available?

**Comment by satanTime** [comment]
[v14.15.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.15.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by ShaneWhittet** [comment]
This release worked for me, until I compiled using a library that depended on Angular 21. 

For ng-mocks@14.15.0, it looks like ng-mocks fails in Angular 21 when the object use signals. Works fine in angular 20.

	TypeError: Cannot read properties of undefined (reading 'Symbol(SIGNAL)')
	    at bindQueryToSignal (node_modules/.pnpm/@angular+core@20.3.15_@angu_89c39e7030e238042fb67a1c68f27806/node_modules/@angular/core/fesm2022/debug_node.mjs:15788:24)
	    at ɵɵcontentQuerySignal (node_modules/.pnpm/@angular+core@20.3.15_@angu_89c39e7030e238042fb67a1c68f27806/node_modules/@angular/core/fesm2022/debug_node.mjs:25956:5)

**Comment by satanTime** [comment]
[v14.15.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.15.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by iamkinetic** [comment]
> This release worked for me, until I compiled using a library that depended on Angular 21. 
> 
> For ng-mocks@14.15.0, it looks like ng-mocks fails in Angular 21 when the object use signals. Works fine in angular 20.
> 
> 	TypeError: Cannot read properties of undefined (reading 'Symbol(SIGNAL)')
> 	    at bindQueryToSignal (node_modules/.pnpm/@angular+core@20.3.15_@angu_89c39e7030e238042fb67a1c68f27806/node_modules/@angular/core/fesm2022/debug_node.mjs:15788:24)
> 	    at ɵɵcontentQuerySignal (node_modules/.pnpm/@angular+core@20.3.15_@angu_89c39e7030e238042fb67a1c68f27806/node_modules/@angular/core/fesm2022/debug_node.mjs:25956:5)
> 

There is already an open issue about Angular 21 compatibility and a couple pull request waiting to be merged to fix it.

This specific issue was about signals and the fix was released.
